// Phosphor icon registry. Import from the SSR entry so icons render in both
// server and client components. Add new icons here (keep it explicit so the
// client bundle only contains icons we use).
import {
  AddressBookIcon,
  AnchorIcon,
  ArrowDownLeftIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowUpIcon,
  ArrowUpRightIcon,
  ArrowsClockwiseIcon,
  ArrowsLeftRightIcon,
  BankIcon,
  BedIcon,
  BeerSteinIcon,
  BellIcon,
  BellRingingIcon,
  BoatIcon,
  BooksIcon,
  BrandyIcon,
  BriefcaseIcon,
  BuildingsIcon,
  CameraIcon,
  CarSimpleIcon,
  CaretDownIcon,
  CaretRightIcon,
  CaretUpDownIcon,
  ChartLineUpIcon,
  ChatTextIcon,
  CheckIcon,
  CheckCircleIcon,
  ChecksIcon,
  ClockCountdownIcon,
  ConfettiIcon,
  CreditCardIcon,
  CurrencyCircleDollarIcon,
  DeviceMobileIcon,
  DotsThreeCircleIcon,
  DotsThreeVerticalIcon,
  DownloadSimpleIcon,
  DropIcon,
  EnvelopeSimpleIcon,
  EyeIcon,
  EyeSlashIcon,
  FileArrowUpIcon,
  FilePdfIcon,
  FileTextIcon,
  FingerprintIcon,
  ForkKnifeIcon,
  GasPumpIcon,
  GearSixIcon,
  GlobeSimpleIcon,
  HandCoinsIcon,
  HandHeartIcon,
  HeadsetIcon,
  HourglassMediumIcon,
  ImageIcon,
  InfoIcon,
  KeyIcon,
  LaptopIcon,
  LifebuoyIcon,
  LightningIcon,
  ListMagnifyingGlassIcon,
  LockSimpleIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MegaphoneIcon,
  MinusIcon,
  PackageIcon,
  PaperPlaneTiltIcon,
  PaperclipIcon,
  PencilSimpleIcon,
  PercentIcon,
  PhoneIcon,
  PintGlassIcon,
  PlugsIcon,
  PlusIcon,
  QuestionIcon,
  ReceiptIcon,
  ScalesIcon,
  SealCheckIcon,
  ShieldCheckIcon,
  ShieldWarningIcon,
  SidebarSimpleIcon,
  SignInIcon,
  SignOutIcon,
  SlidersIcon,
  SparkleIcon,
  SquaresFourIcon,
  TrafficSignIcon,
  TrainIcon,
  TrashIcon,
  UploadSimpleIcon,
  UserIcon,
  UserPlusIcon,
  UsersIcon,
  UsersThreeIcon,
  WalletIcon,
  WarningIcon,
  WarningCircleIcon,
  WineIcon,
  XIcon,
  CopyIcon,
  PrinterIcon,
  ArrowCounterClockwiseIcon,
  CalendarBlankIcon,
  FunnelIcon,
  TruckIcon,
  WarehouseIcon,
  ExportIcon,
  SpinnerIcon,
  CircleNotchIcon,
  ArchiveIcon,
  NotePencilIcon,
  ListChecksIcon,
  LockKeyOpenIcon,
  ProhibitIcon,
  PlayIcon,
  StopIcon,
  EnvelopeIcon,
  QrCodeIcon,
  HashIcon,
  FloppyDiskIcon,
  KeyboardIcon,
  LinkBreakIcon,
  PasswordIcon,
  PulseIcon,
} from "@phosphor-icons/react/ssr";
import type { Icon as PhosphorIcon, IconWeight } from "@phosphor-icons/react";

export const ICONS = {
  AddressBook: AddressBookIcon,
  Anchor: AnchorIcon,
  ArrowDownLeft: ArrowDownLeftIcon,
  ArrowLeft: ArrowLeftIcon,
  ArrowRight: ArrowRightIcon,
  ArrowSquareOut: ArrowSquareOutIcon,
  ArrowUp: ArrowUpIcon,
  ArrowUpRight: ArrowUpRightIcon,
  ArrowsClockwise: ArrowsClockwiseIcon,
  ArrowsLeftRight: ArrowsLeftRightIcon,
  Bank: BankIcon,
  Bed: BedIcon,
  BeerStein: BeerSteinIcon,
  Bell: BellIcon,
  BellRinging: BellRingingIcon,
  Boat: BoatIcon,
  Books: BooksIcon,
  Brandy: BrandyIcon,
  Briefcase: BriefcaseIcon,
  Buildings: BuildingsIcon,
  Camera: CameraIcon,
  CarSimple: CarSimpleIcon,
  CaretDown: CaretDownIcon,
  CaretRight: CaretRightIcon,
  CaretUpDown: CaretUpDownIcon,
  ChartLineUp: ChartLineUpIcon,
  ChatText: ChatTextIcon,
  Check: CheckIcon,
  CheckCircle: CheckCircleIcon,
  Checks: ChecksIcon,
  ClockCountdown: ClockCountdownIcon,
  Confetti: ConfettiIcon,
  CreditCard: CreditCardIcon,
  CurrencyCircleDollar: CurrencyCircleDollarIcon,
  DeviceMobile: DeviceMobileIcon,
  DotsThreeCircle: DotsThreeCircleIcon,
  DotsThreeVertical: DotsThreeVerticalIcon,
  DownloadSimple: DownloadSimpleIcon,
  Drop: DropIcon,
  EnvelopeSimple: EnvelopeSimpleIcon,
  Eye: EyeIcon,
  EyeSlash: EyeSlashIcon,
  FileArrowUp: FileArrowUpIcon,
  FilePdf: FilePdfIcon,
  FileText: FileTextIcon,
  Fingerprint: FingerprintIcon,
  ForkKnife: ForkKnifeIcon,
  GasPump: GasPumpIcon,
  GearSix: GearSixIcon,
  GlobeSimple: GlobeSimpleIcon,
  HandCoins: HandCoinsIcon,
  HandHeart: HandHeartIcon,
  Headset: HeadsetIcon,
  HourglassMedium: HourglassMediumIcon,
  Image: ImageIcon,
  Info: InfoIcon,
  Key: KeyIcon,
  Laptop: LaptopIcon,
  Lifebuoy: LifebuoyIcon,
  Lightning: LightningIcon,
  ListMagnifyingGlass: ListMagnifyingGlassIcon,
  LockSimple: LockSimpleIcon,
  MagicWand: MagicWandIcon,
  MagnifyingGlass: MagnifyingGlassIcon,
  Megaphone: MegaphoneIcon,
  Minus: MinusIcon,
  Package: PackageIcon,
  PaperPlaneTilt: PaperPlaneTiltIcon,
  Paperclip: PaperclipIcon,
  PencilSimple: PencilSimpleIcon,
  Percent: PercentIcon,
  Phone: PhoneIcon,
  PintGlass: PintGlassIcon,
  Plugs: PlugsIcon,
  Plus: PlusIcon,
  Question: QuestionIcon,
  Receipt: ReceiptIcon,
  Scales: ScalesIcon,
  SealCheck: SealCheckIcon,
  ShieldCheck: ShieldCheckIcon,
  ShieldWarning: ShieldWarningIcon,
  SidebarSimple: SidebarSimpleIcon,
  SignIn: SignInIcon,
  SignOut: SignOutIcon,
  Sliders: SlidersIcon,
  Sparkle: SparkleIcon,
  SquaresFour: SquaresFourIcon,
  TrafficSign: TrafficSignIcon,
  Train: TrainIcon,
  Trash: TrashIcon,
  UploadSimple: UploadSimpleIcon,
  User: UserIcon,
  UserPlus: UserPlusIcon,
  Users: UsersIcon,
  UsersThree: UsersThreeIcon,
  Wallet: WalletIcon,
  Warning: WarningIcon,
  WarningCircle: WarningCircleIcon,
  Wine: WineIcon,
  X: XIcon,
  Copy: CopyIcon,
  Printer: PrinterIcon,
  ArrowCounterClockwise: ArrowCounterClockwiseIcon,
  CalendarBlank: CalendarBlankIcon,
  Funnel: FunnelIcon,
  Truck: TruckIcon,
  Warehouse: WarehouseIcon,
  Export: ExportIcon,
  Spinner: SpinnerIcon,
  CircleNotch: CircleNotchIcon,
  Archive: ArchiveIcon,
  NotePencil: NotePencilIcon,
  ListChecks: ListChecksIcon,
  LockKeyOpen: LockKeyOpenIcon,
  Prohibit: ProhibitIcon,
  Play: PlayIcon,
  Stop: StopIcon,
  Envelope: EnvelopeIcon,
  QrCode: QrCodeIcon,
  Hash: HashIcon,
  FloppyDisk: FloppyDiskIcon,
  Keyboard: KeyboardIcon,
  LinkBreak: LinkBreakIcon,
  Password: PasswordIcon,
  Pulse: PulseIcon,
} satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({ name, size = 16, weight = "regular", color, style, className }: {
  name: IconName;
  size?: number;
  weight?: IconWeight;
  color?: string;
  style?: React.CSSProperties;
  className?: string;
}) {
  const C = ICONS[name];
  return <C size={size} weight={weight} color={color} style={{ flex: "none", ...style }} className={className} aria-hidden="true" />;
}
